"""
BOARD_PROPERTIES
"""
LEADERBOARD_SIZE = 10

SCREEN_HEIGHT = 800
SCREEN_LENGTH = 800

BOARD_LENGTH = SCREEN_LENGTH * (2/3)
BOARD_HEIGHT = SCREEN_HEIGHT * (0.8)
BORDER_THICKNESS = 8

NUM_MARBLE_ROWS = 10
NUM_MARBLE_COLUMNS = 4

MAIN_BOARD_X = -SCREEN_LENGTH / 2 + BOARD_LENGTH/2
MAIN_BOARD_Y = SCREEN_HEIGHT/2 - BOARD_HEIGHT/2
MAIN_BOARD_ROWS = 12
MAIN_BOARD_COLUMNS = 6

GUESS_BOARD_LENGTH = SCREEN_LENGTH - BORDER_THICKNESS * 2
GUESS_BOARD_HEIGHT = SCREEN_HEIGHT - BOARD_HEIGHT - BORDER_THICKNESS * 2
GUESS_BOARD_X = 0 - BORDER_THICKNESS
GUESS_BOARD_Y = SCREEN_HEIGHT/2 - BOARD_HEIGHT - GUESS_BOARD_HEIGHT/2
GUESS_BOARD_ROWS = 3
GUESS_BOARD_COLUMN = 9

SCORE_BOARD_LENGTH = SCREEN_LENGTH - BOARD_LENGTH - BORDER_THICKNESS * 2
SCORE_BOARD_HEIGHT = BOARD_HEIGHT
SCORE_BOARD_X = -SCREEN_LENGTH/2 + BOARD_LENGTH + SCORE_BOARD_LENGTH/2
SCORE_BOARD_Y = SCREEN_HEIGHT/2 - BOARD_HEIGHT/2
SCORE_BOARD_ROWS = 12
SCORE_BOARD_COLUMNS = 3
